import React, { Component } from "react"

import PregnancyPDF from "../images/dv_pregnancy.pdf"
import Layout from "../components/layout"
import Accordion from "../components/accordion"

class Pregnancy extends Component {
  render() {
    return (
      <Layout>
      <p><em>These posts were contributed by Rebecca Donley from the <a href="https://www.thehotline.org/tag/pregnancy/">National Domestic Violence Hotline</a> and is a series about pregnancy and abuse.</em></p>
             <Accordion>
        <div label='Prenatal and Early Pregnancy: Tips for Staying Safe'>
          <p>
          Deciding if and when to have a child with a partner is a big decision. This decision can be even more challenging when you are with someone who is threatening, controlling and manipulative. Pregnancy and parenthood cause physical, emotional, financial and social changes, and therefore it is understandable to want stable and reliable partners for support during this transitional time. Unfortunately, some abusers use this transition as an opportunity to gain or maintain power and control through tactics known as reproductive coercion. These tactics can play out differently in every relationship and may seem confusing.

In a healthy relationship, you’re able to talk openly about your feelings around having children without fearing retaliation from your partner if you disagree about the timing or decision to have a child or more children. Differing feelings and desires may lead to a mutual decision to end the relationship, which may be difficult but it would not cause concern for your safety. If you feel afraid to disagree with your partner’s wishes around if and when to have children, this could be a red flag of an abusive relationship.

Whatever your decisions are, you deserve to be safe with your partner. If you are finding that it’s difficult to safely share your choices and needs with your partner, you might turn to other sources for perspective on these decisions. A big piece of any safety plan is determining who is in your support network. If you are thinking of becoming pregnant, or if you are in the early weeks of pregnancy, you may want to consider reaching out to a healthcare provider, such as a nurse or Ob-Gyn, to learn more about how to take care of your physical health needs during this time. You can also discuss with them a plan for getting supportive care that allows space for you to share your needs with them without your partner in the room. Another part of a support network may be a counselor or therapist – someone who you can trust to be nonjudgmental and supportive as you sort out your feelings and concerns around having children with your partner. Trusted friends or family members may also be able to offer support, whatever your decisions may be.

It also can help to get more information from sources that lay out your full range of options. Backline is a national organization that has an informative website around pregnancy and parenting and a toll-free talkline where you can explore a full spectrum of options. Futures Without Violence also has a lot of great information on their website, including projects dedicated to increasing reproductive and sexual health. Planned Parenthood has information on their website about factors and information you may want to take into account when considering pregnancy. The Hotline is also here for you 24/7 by phone (1-800-799-7233) or chat (7 a.m. to 2 a.m. CT) to brainstorm more ideas for support and information.

While putting together your support network and exploring resources, it’s important to consider whether your partner may be trying to monitor your activities. You may want to reach out for support on a phone or computer that your partner can not access. If you share a phone account, consider getting a go phone so your partner cannot observe the numbers that you’ve called on your bill. You may also want to use a work or public computer or a friend’s smartphone to explore online resources instead of a computer or smartphone that your partner could monitor.

These decisions are big, and you deserve access to the support and information that can help you choose the options that feel best to you. You are the expert in your situation and are the one best-suited to make these decisions. Whatever you decide, The Hotline is here for you every step of the way.

Deciding if and when to have a child with a partner is a big decision. Pregnancy and parenthood cause physical, emotional, financial and social changes, which can become even more challenging when your partner is abusive toward you.

If you are pregnant and in an abusive relationship, you deserve to prioritize your safety. We can help you create a safety plan and locate resources in your area, if available. For Deaf, DeafBlind, or DeafDisabled callers, we are available 24/7 at 1-855-812-1001, email at nationaldeafhotline@adwas.org or via live online chat on this website or our Facebook page.

Check out the blog posts on The National Domestic Violence Hotline like Pregnancy & Abuse for safety planning tips, additional resources and information on pregnancy and abuse.
          </p>
        </div>
        <div label='Pregnancy and Abuse: Planning a Safe Child Birth'>
        <p>
        For many first time parents, childbirth is an exciting yet frightening event. While there are many ways to prepare yourself for the birth of your child, everyone has a different version of the perfect birth, so these steps will vary from person to person.  Some people create a birth plan to outline what they would like to happen during and immediately following birth. A birth plan can include measures for safety if you are also concerned about the impact or role of an abusive partner during the birth.

As you are creating this plan, consider the allies that you will have available during the birth. If you plan to give birth at a hospital, doctors and nurses will likely be present during much of your labor process. If you are giving birth at a birthing center or at home, you may have a midwife present. Depending on your prenatal care options, you may have been able to inform these professionals about your concerns about the abuse. If not, contacting the professionals beforehand and planning some items to add to your birth plan for safety may be a possibility. You also might have a professional like a doula for support at the birth. Birth doulas provide support at hospitals, birth centers or home births, and unlike a doctor or nurse who may be supporting several patients and present only during certain parts of labor, your doula will stay with you throughout your labor process. Though doulas may not have training in domestic violence or supporting someone who is experiencing abuse, you still may be able to reach out to them for added support during your labor. While doula costs may not be covered by insurance, some doulas may be able to provide services pro bono or on a sliding scale. If you do not have a birth doula, you may want to identify a family member or friend to take on the role of labor support. When considering who to ask, keep in mind that you may want someone who will safety plan with you as opposed to for you.

Childbirth requires a lot of energy and focus. Even if you have a c-section planned in advance, that’s a major surgery that deserves your full attention. No matter your birth plan, it’s important that you be able to fully access your reserves without having distractions. If you feel like your abusive partner or ex-partner will attempt to prevent you from taking necessary steps for a safe and stress-free birth, consider adding strategies to your birth plan that will refocus and energize you. Different strategies work for different people, so practice these in advance to see what is most effective for you. These include movement exercises, breathing exercises, guided meditation or relaxation narratives, listening or singing to music and repeating positive affirmations. The key is that you are able to stay relaxed and positive.

If you have left the relationship, or go into labor while your partner isn’t present, you may determine that preventing them from finding out that you are giving birth is the safest thing for you and your child. You may be able to do this by only alerting your labor support person when you go into labor, and ensure that they know to not share this information with anyone else. When determining where you will give birth, you may want to consider whether your partner or ex knows your due date, and if they will try reaching out to area hospitals, birth centers or your support network to try find you. Once you determine a plan, let the staff at the place where you give birth know to alert you if someone tries looking for you, as well as to not provide any information about your presence or status. Give them a picture of your partner/ex, and ask that staff alert you if anyone matching their description is reported in the area. If you are giving birth outside the home, you may want to take a cab or have a friend or family member take you in a vehicle that your partner/ex will not recognize. When you leave the facility, ask your labor support to check the parking lot to ensure that your partner/ex is not waiting for you. While it is understandable that you would want to share information of your birth with social networks, consider safety before sharing updates or information. Pictures online can often be viewed by friends of friends, even if the abuser is blocked. If family and friends visit, ask them to wait on posting any photos that they take with you or the baby until after you’ve returned home.

You may need to have a plan for staying safe with the abuser present during labor as well. Creating activities to occupy your partner, like asking them to contact family and friends or pick up items from the store if they are distracting you, may be one strategy to create space for you to focus. As part of your safety measures in your birth plan, you could determine a code word to use with your doctor, nurse, midwife, doula or other labor support to alert them if you are feeling unsafe and would like your abuser removed from the room. You could also have a friend or family member stay with your partner to prevent them from interrupting your focus during childbirth. Brainstorming other strategies ahead of time is key because you will want your full energy to go towards ensuring a safe and peaceful birth. Even if your partner has limited your birth planning options, you may be able to mentally prepare yourself by researching childbirth and making a personal safety and self-care plan for each stage. Obtaining access to a phone to dial 911 in the case that your partner has prohibited you to leave the home to have the baby may be one part of an emergency safety plan. Identifying a room where you feel most safe and relaxed to labor, and preparing it in advance with the items and materials that you will need is another strategy to reduce stress during labor without external support.

Whatever your circumstance or needs, The Hotline is available to help you, whether that’s identifying local options or national resources that may enhance your safety, developing a personalized safety plan that helps you maintain your reserves for childbirth, or providing emotional support and validation during the last phase of pregnancy. For Deaf, DeafBlind, or DeafDisabled callers, we are available 24/7 at 1-855-812-1001, email at nationaldeafhotline@adwas.org or via live online chat on this website or our Facebook page.
        </p>
        </div>
        <div label="Staying Physically, Emotionally and Financially Safe During Pregnancy">
          <p>
          While often portrayed as a magical, happy time, pregnancy—with the associated physical, emotional, social, and financial changes—can be challenging, even with a supportive partner in a healthy relationship. Because an abusive partner may see the unpredictability of pregnancy as an opportunity to increase power and control, if you’re pregnant it’s important to explore options to enhance your physical, emotional, financial and legal safety.

Your physical safety needs may change as pregnancy progresses; what may seem safe at one point may not feel that way a few weeks later. Getting prenatal care may be a way to maintain both your and the baby’s health during this time. It also may be a way to connect with a service provider that you can turn to if you are concerned for your safety. If you are unsure about accessing prenatal care, you may be able to get more information by contacting <a href="http://www.211.org/services/health">211</a>, a local resource line available in most communities. You can also sign up for <a href="https://text4baby.org/">Text4Baby</a>, a free service that sends you tips about staying healthy during pregnancy up through your child’s first birthday. If you have concerns about not being insured, you may be able to get insurance through the <a href="https://www.healthcare.gov/">Affordable Care Act (ACA)</a>. Survivors of domestic violence can enroll at the <a href="https://www.healthcare.gov/">healthcare.gov</a> website at any time, using the Special Enrollment Period (SEP). For more information about this option, visit the What’s New? area of the <a href="http://www.healthcaresaboutipv.org/">Health Cares About IPV</a> website.

During pregnancy, your center of gravity shifts and joints loosen to allow for easier childbirth. This can make getting around more difficult. If you live with the abuser, consider mapping the safest routes out of the home or apartment from the rooms where you spend the most time. Try avoiding rooms with weapons, hard surfaces and areas near stairs. If it is becoming difficult to drive, consider identifying some safe people that you can contact if you need transportation. Keeping cab or bus fare stowed in a packed bag may be another way to get out quickly if needed.

Protecting and maintaining your emotional energy during this time is also important and closely linked to physical safety, as stress can adversely impact your pregnancy. Creating a self-care plan is one way to achieve this. Some people use prenatal yoga, walking in nature, journaling, art or spending time with loved ones as part of their self-care. Creating social connections with other parents can be particularly important during pregnancy. Meetup.com is a website where you may be able to a group of parents expecting children with a due date close to yours. Other parenting and social media websites may have similar groups that you can join to find support and connection. If finding a group online doesn’t fit your needs, you could ask your healthcare provider to ask about classes or programs for expecting parents. Seeking out the support of a counselor may be an additional way to get perspective during this time. The Hotline can offer information about local domestic violence programs that offer counseling and support groups. If you’re looking for counselors that specialize in other areas, GoodTherapy is a website that offers assistance finding a local counselor, as well as articles and resources on issues that impact emotional well-being, including during pregnancy.

Pregnancy is also a time when financial and legal options begin to shift. Knowing your rights around these issues is a first step to creating a plan to protect yourself and your new child. While workplaces may differ in their support for pregnant employees, there are certain employment laws that they must follow. The Department of Labor’s Women’s Bureau has a website where you can review your rights during pregnancy and as a new parent. Some state domestic violence coalitions also have dedicated projects that offer support for protecting yourself financially. One great example is the Economic Justice Project of the Washington State Coalition Against Domestic Violence called Get Money, Get Safe, which offers general tips on banking, credit and other issues for survivors of domestic violence. Knowing your options regarding custody can also be confusing, especially if you have several plans that you are considering for both your and your future child’s safety. WomensLaw offers a wealth of legal information including custody information and parental kidnapping laws searchable by state.

Safety plans are not one size fits all. Each person has a right to safety and a right to define how that will look, and these suggestions are not meant to serve as a guarantee or a direction. At The Hotline, we believe that you are the foremost expert in your situation. If you see some ideas that seem fitting and would like to expand on them, you’re always welcome to call us 24/7 at 1-855-812-1001, email us at nationaldeafhotline@adwas.org or chat live online on this website or our Facebook page. to fully discuss creating a personalized safety plan.
          </p>
        </div>
      </Accordion>
      <br/>
     <h3>Pregnancy and Domestic Violence Facts</h3>
      <embed src={PregnancyPDF} type="application/pdf" width="100%" height="600px" alt="pdf on DV & pregnancy" />
      </Layout>
    )
  }
}

export default Pregnancy